### ISSUE TITLE
u7s upgrade  (kubeadm)

### ISSUE THREAD

**Issue by cheungsuifai** [rootless-containers/usernetes#270] opened 2022-11-29 09:49 UTC
Within k8s, the cluster is upgrade with the kubeadm command.

But the cluster is deployed via "hard way" in u7s, and kubeadm is excluded in the release.

So is the only way to upgrade u7s cluster to **undeploy-redeploy with the newer version** ?
Is there any plan for **introducing kuebadm** and **providing a easier upgrade method**?

**Comment by AkihiroSuda** [comment] 2022-11-30 11:25
Help wanted to support kubeadm.

**Comment by AkihiroSuda** [comment] 2022-11-30 11:25
Duplicate of
- #69

**Closed by AkihiroSuda** 2022-11-30 11:25 UTC
Labels: duplicate, help wanted
